### ISSUE TITLE
Handle async tests

### ISSUE THREAD

**Issue by flegall** [jsGiven/jsGiven#12]
Currently jsGiven does not handle async tests, these tests become more or less necessary when it comes to integrations tests or end-to-end tests.

I don't think the scenarios is the place where asynchronicity should take place.
The scenarios have to remain readable, even if the .then() calls or await keywords will not appear in the report, I don't think they should appear in the scenarios code.

I would rather see them in the stages methods.
The main problem is that if the scenario remains synchronous, the stage methods should also be.

**Comment by janschaefer** [comment]
This is quite difficult to achieve. I solved it in the following way in GivenJS:
- scenarios are not executed directly, instead the method calls are 'recorded' without actually executing the bodies of the step methods
- after everything is 'recorded' the scenario is executed step-by-step
- if a stage method has as a last parameter a callback function it is assumed to be asynchronous and handled specially by the execution mechanism

Advantage of that approach:
- the scenario stays clean and contains no asynchronous handling code

Disadvantage:
- debugging becomes more difficult

**Comment by flegall** [comment]
Fun, this is more or less what I had in mind :)

I agree with you with the advantages and disadvantages.

I would treat any stage method as asynchronous as long as it returns a promise. I would stay away from callbacks as in modern javascript:
- there is a tendency to uses promise or async functions (these are handy because from a caller point of view they are regular functions that return promises), 
- detecting "callback" from arguments names is fragile. 

We can still have a utility function or decorator that 'promisify' functions with a callback parameter last argument.

Also recording the stages method calls can be practical in order to implement error handling : https://github.com/jsGiven/jsGiven/issues/55

**Comment by janschaefer** [comment]
ok, I completely agree that the promise approach is the better one :-)

**Comment by flegall** [comment]
Finally I've chosen to 
- introduce a static method helper doAsync()
- recording step methods call and then executing them

It can be used like this : https://github.com/jsGiven/jsGiven/blob/master/js-given/spec/async-scenarios.spec.js#L38

Some work is still needed for error reporting #55 (collecting step method names and arguments instead of collections functions to execute)

And some documentation should be written before closing this :)

**Comment by flegall** [comment]
This seems ok for now, after some testing at work, I'm happy with the current implementation.
