### ISSUE TITLE
Implement error handling

### ISSUE THREAD

**Issue by janschaefer** [jsGiven/jsGiven#55]
In particular, if one step method fails, the rest of the scenario should still appear in the report,

**Comment by flegall** [comment]
How is it implemented in JGiven ? 

Is the scenario execution full asynchronous ? This way you have the scenario plan already at startup from the DSL execution? Or is the rest of the scenario executed silently and the error is thrown at the end of the scenario execution ?

**Comment by janschaefer** [comment]
In JGiven it is the former one. Exceptions are caught and the scenario is continued by skipping the excecution of the method bodies. But as you already said in #12 recording seems to be the better approach for jsgiven.

**Comment by flegall** [comment]
Finally implemented on master, it will be available in 0.1.5 !

**Comment by flegall** [comment]
Implemented in 0.1.5 !
